name: Build and deploy Node.js app to Azure Web App - angularPruebas


on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: node --max-old-space-size=2048 node_modules/@angular/cli/bin/ng build --configuration production

      - name: Check build output
        run: ls -la dist/browser

      - name: Zip artifact for deployment
        run: |
          cd dist
          ZIP_FOLDER=$(ls)  # Obtiene el nombre de la carpeta dentro de dist
          zip -r ../release.zip "$ZIP_FOLDER"
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d wwwroot


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AFB519C629524D4BAB728ADB01B50F62 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_791D1D7F86F048DB9AE3C85975232D19 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16D45923A80A4652B527F54328251700 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'angularPruebas'
          package: wwwroot
