name: Angular CI/CD

trigger:
  branches:
    include:
      - main  # Asegúrate de que tu rama principal sea "main"

pr:
  branches:
    include:
      - main  # Para los pull requests también

jobs:
  - job: build
    displayName: 'Build and Deploy Angular App'
    pool:
      vmImage: 'ubuntu-latest'  # Cambia a 'windows-latest' si usas un agente Windows

    steps:
    - task: Checkout@2  # Tarea de Azure DevOps para hacer checkout del código

    - task: NodeTool@0  # Tarea de Azure DevOps para configurar Node.js
      inputs:
        versionSpec: '18.x'  # Versión de Node.js a instalar

    - script: |
        echo "Mostrando el contenido del directorio actual:"
        pwd  # Muestra el directorio actual
        echo "Mostrando el contenido del directorio:"
        ls -la  # Lista los archivos en el directorio actual
      displayName: 'Verificar el directorio actual y su contenido'

    - script: |
        npm install  # Instalar dependencias
      displayName: 'Instalar dependencias'

    - script: |
        npm run build -- --configuration production  # Construir la aplicación
      displayName: 'Construir aplicación Angular'

    - task: PublishBuildArtifacts@1  # Publicar artefactos
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Asegúrate de que esta ruta esté configurada
        ArtifactName: 'dist'
        publishLocation: 'Container'

    - script: |
        echo "Build completado y artefactos publicados"
      displayName: 'Finalizar Pipeline'
